apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-query-ingress
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: "85.230.96.242/32"
spec:
  ingressClassName: nginx
  rules:
  - host: jaeger.alignai.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jaeger
            port:
              number: 16686
  tls:
  - hosts:
    - jaeger.alignai.com
    secretName: jaeger-query-tls
